### ISSUE TITLE
Rename `contrib` repository to `evolution`

### ISSUE THREAD

**Issue by kris-nova** [falcosecurity/evolution#14]
**Motivation**

Following https://github.com/falcosecurity/falco/pull/1184 I would like for this repository to be a repository that holds the following.

 - Documentation on the evolution process (what is `contrib`, `repo`, and `official`? How do they work? How do you progress?)
 - A `/contrib` directory which serves as the storage for what is now this repository
 - A `/official` directory with documentation about our current official support
 - A `/repo` directory (maybe with YAML like [Kubernetes uses for slack channels](https://github.com/kubernetes/community/blob/master/communication/slack-config/channels.yaml)) that defines our repositories and OWNERS 
 - Links to artifacts

**Feature**

Can we rename this repository and structure it in such a way that we can automate some of this in the future? 

**Alternatives**

**Additional context**

**Comment by leodido** [comment]
I'd call it "yamloution" 😃 

Anyway, I agree on this proposal.

The only thing I'd add is: it woud be rad if the OWNERS listed into the `/repo` YAMLs would be automatically collected from the OWNERS file we already have in place.
Don't you think? :)

**Comment by maxgio92** [comment]
So the `/official` directory in this repo will contain documentation of the projects that probably passed through the `/repository` step (as for [this](https://github.com/falcosecurity/contrib/issues/13#issuecomment-624774787)), and which sources probably have a dedicated repository, am I right?

**Comment by leogr** [comment]
@maxgio92 yep, I think so

@leodido I strongly agree because you said "automatically" :cupid: :stuck_out_tongue_closed_eyes: 

@kris-nova I agree too, but why `/official` could not be implemented as like as `/repo`? I'd like the idea of having official documentation in their own repos with `/official` that just indexes them.

**Comment by nibalizer** [comment]
Overall I agree. For `/repo` I have done this on a few different projects so 100% agree we need the big yaml file(s) that have metadata about the repos. I would like to see that in the same repo as our [prow configs](https://github.com/falcosecurity/test-infra/blob/master/prow/config/configs.yaml#L122) since it's a lot of the same data and having them in the same repo makes it possible to set up checks and avoid simple 'added it in one place, didn't add it in the other place' errors. I don't which repo that is very much but having them close to each other makes sense I think.

**Comment by kris-nova** [comment]
Closing after the community call we have migrated pdig to github.com/falcosecurity/pdig and are following the official Falco project template and guidelines.

Welcome to Falco :)

**Comment by fntlnz** [comment]
I like the new name and reasoning behind it - :+1:

**Comment by maxgio92** [comment]
I agree with @nibalizer to keep the `/repo` data centralized, I don't know if the [test-infra](https://github.com/falcosecurity/test-infra) could be the right one.

**Comment by leodido** [comment]
I've changed my mind on the subdirectories `repo/` and `official/` by observing the eventual final result in the PR.

It seems to me they could only cause maintenance burden and confusion.

Everything here is "sandbox".
Everything having its own repo (with its own OWNERS) is "incubated".
Every artifact provided by the main Falco repo (and document so in the website) is "official".

**Comment by leogr** [comment]
Hey @leodido 

IMHO we can proceed with renaming this repo then merge the PR #24
