### ISSUE TITLE
add  ekscloudwatch into falco helm chart to ship EKS audit logs to falco

### ISSUE THREAD

**Issue by ismailyenigul** [falcosecurity/evolution#45]
**Motivation**

There is no way for Falco to inspect the EKS audit events directly, Because they are being sent to CloudWatch only.
We need to ship EKS api logs from cloudwatch to falco.

https://github.com/sysdiglabs/ekscloudwatch works fine with falco. 
We can add this image, and it's deployment to  falco helm chart at https://github.com/falcosecurity/charts/tree/master/falco
I am happy to work on this integration.

**Comment by maxgio92** [comment]
Hi @ismailyenigul , thank you. This is a good idea.
If you want to add an integration I think [this](https://github.com/falcosecurity/evolution/tree/master/integrations) is the correct repository to open a PR to.
Instead, if you want to add support to the helm chart you can open a PR to the [charts repository](https://github.com/falcosecurity/charts/tree/master/falco).

What do you think @leogr?

**Comment by leogr** [comment]
Hi,

If I understood correctly the intent here is to add support for EKS audit events to the helm chart. That would be really great! 

Unfortunatelly, https://github.com/sysdiglabs/ekscloudwatch is not maintained anymore (it has been confirmed by the original maintainers - @danpopSD correct me if I'm wrong).

So, IMHO we cannot simply integrate it in the helm Falco's chart ("incubating" status), since nobody will fix bugs and it can break at anytime in the future.
It's just about maintainability (imagine if the integration breaks and we cannot fix the issue in the helm chart, what will we do then?).

That being said, I agree that integrating with EKS audit log is a good idea anyway. So below some thoughts:

- It would be great if someone volounters to maintain a new project for EKS audit log integration (from scratch, or derivated from https://github.com/sysdiglabs/ekscloudwatch). I don't have enough time to do that, but if someone volounters I will do my best to help.
- Meanwhile, I believe it's still possible to use https://github.com/sysdiglabs/ekscloudwatch as a separate deployment (without modifying the helm chart).


It's just my opinion anyway. It would be great to get feedback from others @falcosecurity/charts-maintainers too.

**Comment by bygui86** [comment]
I agree with @leogr in general, but I would prefer to have a more agnostic k8s-event-exporter. It would take events directly from k8s, watching resources and routing them to Falco or somewhere else.

Normally I use GCP and it's pretty complicated and difficult to maintain the infrastructure to route GKE events to Falco (inside k8s). For this reason I would avoid involving EKS/GKE, relying only on what's offered by k8s.
